name: React Build

on:
  push:
    branches:
      - master # change if your branch name is different
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # match your local Node version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

